# Run for this repository:
#   pre-commit install
# Check without committing:
#   pre-commit run --all-files
# Hooks:
#   https://pre-commit.com/hooks.html
repos:
# pre-commit builtins
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    # committing credentials
    -   id: detect-private-key
    # files larger than 500kB
    -   id: check-added-large-files
    # commits to master or main branch
    -   id: no-commit-to-branch
    # merge conflict strings
    -   id: check-merge-conflict
    # no debugging statements
    -   id: debug-statements
    # tests in format test*.py
    -   id: name-tests-test
        args: [--django]